# Generated by Django 5.0.1 on 2024-07-04 13:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id_conge', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('delete_date', models.DateTimeField(null=True)),
                ('update_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'Conge',
            },
        ),
        migrations.CreateModel(
            name='CRA',
            fields=[
                ('id_cra', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_cra', models.DateField(auto_now_add=True)),
                ('start_date', models.DateField(default=None)),
                ('end_date', models.DateField(default=None)),
                ('categorie', models.CharField(choices=[('1', 'Mission'), ('2', 'congé')], default='1', max_length=255)),
            ],
            options={
                'db_table': 'Compte_rendu_activite',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id_goupe', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_users', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Type_collaborateur',
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id_mission', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_mission', models.DateTimeField()),
                ('end_mission', models.DateTimeField()),
                ('client_mission', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('users_name', models.CharField(max_length=255)),
                ('users_fname', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('delete_date', models.DateTimeField(null=True)),
                ('update_date', models.DateTimeField(null=True)),
                ('users_phone', models.CharField(max_length=255, null=True)),
                ('users_company', models.CharField(max_length=255)),
                ('users_mail', models.CharField(max_length=50, unique=True)),
                ('users_type', models.CharField(max_length=255)),
                ('users_password', models.CharField(max_length=128)),
                ('users_region', models.CharField(max_length=255)),
                ('users_address', models.CharField(max_length=255)),
                ('users_postal', models.CharField(max_length=10, null=True)),
                ('users_is_active', models.BooleanField(default=True)),
                ('users_preavis', models.BooleanField(default=True)),
                ('verifopt', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserTwoFactorAuthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_secret', models.CharField(max_length=255)),
                ('session_identifier', models.CharField(default='default_value', max_length=255)),
                ('qr_code', models.CharField(default='None', max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_auth_data', to='pulls.user')),
            ],
            options={
                'db_table': 'pulls_usertwofactorauthdata',
            },
        ),
    ]
